name: Update GitHub Profile README

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Learning Streak
        run: |
          TODAY=$(date +"%Y-%m-%d")
          echo "📅 Learning Streak Updated: $TODAY" > streak.txt
          git add streak.txt

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-github-username"
          git commit -m "Updated Learning Streak 🚀" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git main
